server:
    port: 7080
spring:
    application:
        name: zipkinclient
    sleuth:
        web:
            client:
                enabled: true   # 设置开启请求跟踪
        sampler:
            probability: 1.0    # 设置采用比例，默认为1.0
    zipkin:
        base-url: http://localhost:7070/    # zipkin server 地址
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/